import type { Room } from '@/types'

const supabaseUrl  = process.env.NEXT_PUBLIC_SUPABASE_URL  || ''
const supabaseAnon = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''

export function isMockMode() {
  return !supabaseUrl || !supabaseAnon
}

export async function getSupabaseClient() {
  if (isMockMode()) return null
  const { createClient } = await import('@supabase/supabase-js')
  return createClient(supabaseUrl, supabaseAnon)
}

export const MOCK_ROOMS: Room[] = [
  { id:1,  source:'badi',      external_id:'badi-1',  titulo:'Hab. individual junto a Complutense — baño privado', descripcion:'Habitación luminosa en piso de 3 personas, muy tranquilo. A 8 minutos andando de la Complutense.', ciudad:'madrid',    barrio:'Moncloa',     lat:40.4418, lng:-3.7198, precio:420, tipo:'individual', metros:12, bano_privado:true,  erasmus_ok:true,  disponible_desde:'2025-09-01', url_original:'https://badi.com/rooms/mock-1?ref=TU_REF', thumbnail_url:null, comision_tipo:'porcentaje', comision_valor:0.15, activo:true, scraped_at:new Date().toISOString() },
  { id:2,  source:'badi',      external_id:'badi-2',  titulo:'Hab. en piso de 4 personas — Chamberí tranquilo',    descripcion:'Piso luminoso en Chamberí, 4 habitaciones. Lavadora, cocina equipada.', ciudad:'madrid',    barrio:'Chamberí',    lat:40.4312, lng:-3.7003, precio:310, tipo:'compartida', metros:10, bano_privado:false, erasmus_ok:false, disponible_desde:'2025-08-01', url_original:'https://badi.com/rooms/mock-2?ref=TU_REF', thumbnail_url:null, comision_tipo:'porcentaje', comision_valor:0.15, activo:true, scraped_at:new Date().toISOString() },
  { id:3,  source:'badi',      external_id:'badi-3',  titulo:'Estudio completo Ciudad Universitaria',              descripcion:'Estudio independiente con cocina propia y baño privado.', ciudad:'madrid',    barrio:'Argüelles',   lat:40.4368, lng:-3.7162, precio:590, tipo:'estudio',    metros:28, bano_privado:true,  erasmus_ok:true,  disponible_desde:'2025-09-01', url_original:'https://badi.com/rooms/mock-3?ref=TU_REF', thumbnail_url:null, comision_tipo:'porcentaje', comision_valor:0.15, activo:true, scraped_at:new Date().toISOString() },
  { id:4,  source:'uniplaces', external_id:'uni-4',   titulo:'Estudio moderno Lavapiés — 15 min Complutense',      descripcion:'Estudio reformado con aire acondicionado y portero automático.', ciudad:'madrid',    barrio:'Lavapiés',    lat:40.4082, lng:-3.7041, precio:550, tipo:'estudio',    metros:25, bano_privado:true,  erasmus_ok:true,  disponible_desde:'2025-09-01', url_original:'https://uniplaces.com/accommodation/mock-4?ref=TU_REF', thumbnail_url:null, comision_tipo:'fijo', comision_valor:45, activo:true, scraped_at:new Date().toISOString() },
  { id:5,  source:'uniplaces', external_id:'uni-5',   titulo:'Hab. en piso de estudiantes Malasaña',               descripcion:'Piso compartido en el corazón de Malasaña. Limpieza semanal incluida.', ciudad:'madrid',    barrio:'Malasaña',    lat:40.4224, lng:-3.7054, precio:375, tipo:'compartida', metros:11, bano_privado:false, erasmus_ok:true,  disponible_desde:'2025-10-01', url_original:'https://uniplaces.com/accommodation/mock-5?ref=TU_REF', thumbnail_url:null, comision_tipo:'fijo', comision_valor:45, activo:true, scraped_at:new Date().toISOString() },
  { id:6,  source:'badi',      external_id:'badi-6',  titulo:'Hab. luminosa junto a UPF Poblenou',                 descripcion:'Habitación exterior con balcón, a 5 minutos andando de UPF.', ciudad:'barcelona', barrio:'Poblenou',    lat:41.4036, lng:2.1981,  precio:490, tipo:'individual', metros:14, bano_privado:false, erasmus_ok:true,  disponible_desde:'2025-09-01', url_original:'https://badi.com/rooms/mock-6?ref=TU_REF', thumbnail_url:null, comision_tipo:'porcentaje', comision_valor:0.15, activo:true, scraped_at:new Date().toISOString() },
  { id:7,  source:'badi',      external_id:'badi-7',  titulo:'Piso compartido junto a UB Diagonal',                descripcion:'Habitación en piso de 3 estudiantes. Metro María Cristina a 3 minutos.', ciudad:'barcelona', barrio:'Les Corts',   lat:41.3838, lng:2.1341,  precio:360, tipo:'compartida', metros:11, bano_privado:false, erasmus_ok:false, disponible_desde:'2025-08-01', url_original:'https://badi.com/rooms/mock-7?ref=TU_REF', thumbnail_url:null, comision_tipo:'porcentaje', comision_valor:0.15, activo:true, scraped_at:new Date().toISOString() },
  { id:8,  source:'uniplaces', external_id:'uni-8',   titulo:'Hab. privada Gràcia — 10 min UB',                    descripcion:'Habitación con baño privado en piso de diseño en Gràcia.', ciudad:'barcelona', barrio:'Gràcia',      lat:41.4044, lng:2.1534,  precio:510, tipo:'individual', metros:13, bano_privado:true,  erasmus_ok:true,  disponible_desde:'2025-09-01', url_original:'https://uniplaces.com/accommodation/mock-8?ref=TU_REF', thumbnail_url:null, comision_tipo:'fijo', comision_valor:45, activo:true, scraped_at:new Date().toISOString() },
  { id:9,  source:'uniplaces', external_id:'uni-9',   titulo:'Estudio amueblado Eixample — UPF 5 min',             descripcion:'Estudio moderno en Eixample Esquerra. Totalmente amueblado.', ciudad:'barcelona', barrio:'Eixample',    lat:41.3797, lng:2.1487,  precio:680, tipo:'estudio',    metros:32, bano_privado:true,  erasmus_ok:false, disponible_desde:'2025-09-01', url_original:'https://uniplaces.com/accommodation/mock-9?ref=TU_REF', thumbnail_url:null, comision_tipo:'fijo', comision_valor:45, activo:true, scraped_at:new Date().toISOString() },
  { id:10, source:'badi',      external_id:'badi-10', titulo:'Estudio con terraza zona 22@ — UPF 5 min',           descripcion:'Estudio con terraza privada en el barrio tecnológico 22@.', ciudad:'barcelona', barrio:'22@',         lat:41.4023, lng:2.1921,  precio:640, tipo:'estudio',    metros:30, bano_privado:true,  erasmus_ok:true,  disponible_desde:'2025-10-01', url_original:'https://badi.com/rooms/mock-10?ref=TU_REF', thumbnail_url:null, comision_tipo:'porcentaje', comision_valor:0.15, activo:true, scraped_at:new Date().toISOString() },
  { id:11, source:'badi',      external_id:'badi-11', titulo:'Hab. individual campus Tarongers UV',                descripcion:'Habitación con baño privado a 3 minutos del campus Tarongers.', ciudad:'valencia',  barrio:'Algirós',     lat:39.4795, lng:-0.3488, precio:340, tipo:'individual', metros:13, bano_privado:true,  erasmus_ok:true,  disponible_desde:'2025-09-01', url_original:'https://badi.com/rooms/mock-11?ref=TU_REF', thumbnail_url:null, comision_tipo:'porcentaje', comision_valor:0.15, activo:true, scraped_at:new Date().toISOString() },
  { id:12, source:'badi',      external_id:'badi-12', titulo:'Piso 4 hab. muy céntrico — cerca UV y UPV',          descripcion:'Habitación en piso compartido en Ruzafa, barrio de moda en Valencia.', ciudad:'valencia',  barrio:'Ruzafa',      lat:39.4617, lng:-0.3718, precio:270, tipo:'compartida', metros:10, bano_privado:false, erasmus_ok:false, disponible_desde:'2025-08-01', url_original:'https://badi.com/rooms/mock-12?ref=TU_REF', thumbnail_url:null, comision_tipo:'porcentaje', comision_valor:0.15, activo:true, scraped_at:new Date().toISOString() },
  { id:13, source:'uniplaces', external_id:'uni-13',  titulo:'Hab. doble uso individual — barrio universitario',   descripcion:'Habitación amplia en Benimaclet, barrio universitario por excelencia.', ciudad:'valencia',  barrio:'Benimaclet',  lat:39.4851, lng:-0.3614, precio:330, tipo:'individual', metros:12, bano_privado:false, erasmus_ok:true,  disponible_desde:'2025-09-01', url_original:'https://uniplaces.com/accommodation/mock-13?ref=TU_REF', thumbnail_url:null, comision_tipo:'fijo', comision_valor:45, activo:true, scraped_at:new Date().toISOString() },
]
